### ISSUE TITLE
lib32-gst-bad-ugly

### ISSUE THREAD

**Issue by gulafaran** [ahmubashshir/pkgbuilds#14]
after 1.24.0-1 change it wont build anymore

==> Starting prepare()...
Applied patch to 'meson.build' with conflicts.
Applied patch to 'meson_options.txt' cleanly.
Applied patch to 'meson.build' with conflicts.
U meson.build
U meson.build
==> ERROR: A failure occurred in prepare().
    Aborting...
 -> error making: lib32-gst-bad-ugly-exit status 4
 -> Failed to install the following packages. Manual intervention is required:

**Comment by ahmubashshir** [comment]
[0001-Allow-disabling-gstreamer.patch.gz](https://github.com/ahmubashshir/pkgbuilds/files/14576460/0001-Allow-disabling-gstreamer.patch.gz)

Can you again with this patch? if this patch fixes the issue, I'll push it.

**Comment by gulafaran** [comment]
it got it closer

Applied patch to 'meson.build' cleanly.
Applied patch to 'meson_options.txt' cleanly.
Applied patch to 'subprojects/gst-editing-services/meson.build' with conflicts.
Applied patch to 'subprojects/gst-plugins-good/tests/check/elements/flvmux.c' cleanly.
Applied patch to 'subprojects/gst-python/meson.build' cleanly.
Applied patch to 'subprojects/gst-rtsp-server/tests/check/meson.build' cleanly.
Applied patch to 'subprojects/gstreamer-vaapi/meson.build' cleanly.
U subprojects/gst-editing-services/meson.build

some conflict in gst-editing-service

**Comment by gulafaran** [comment]
which seems to be the hack to disable broken texts, disabling that patch im then some build options has also changed. 

gstreamer/meson.build:1:0: ERROR: Unknown options: "omx"

commenting out -D omx=disabled im hitting

gstreamer/subprojects/gst-plugins-bad/gst-libs/gst/webrtc/nice/meson.build:16:14: ERROR: Subproject "subprojects/libnice" required but not found.

**Comment by gulafaran** [comment]
installing lib32-libnice solved that, and then im hitting 
gst-plugins-bad| Run-time dependency ltc found: NO (tried pkgconfig and cmake)
gst-plugins-bad| Run-time dependency libajantv2 found: NO (tried pkgconfig and cmake)

so added like arch gst-plugins-bad
		-D gst-plugins-bad:aja=disabled
		-D gst-plugins-bad:mfx_api=oneVPL
		-D gst-plugins-bad:qt6d3d11=disabled
		
got me past that, then i had to install lib32-svt-av1 because gst-plugins-bad| Run-time dependency svtav1enc found: NO (tried pkgconfig and cmake)

i also had to -D gst-plugins-bad:lc3=disabled because no lib32

in short i landed on these changes in the PKGBUILD until it built 

```
diff --git a/PKGBUILD b/PKGBUILD
index 12a693d..d533767 100644
--- a/PKGBUILD
+++ b/PKGBUILD
@@ -113,7 +113,7 @@ prepare() {
 	git apply -3 ../0001-Allow-disabling-gstreamer.patch
 
 	# Disable broken tests
-	git apply -3 ../0002-HACK-meson-Disable-broken-tests.patch
+	#git apply -3 ../0002-HACK-meson-Disable-broken-tests.patch
 }
 
 _fix_pkgconf() {
@@ -148,7 +148,8 @@ build() {
 		-D gst-examples=disabled
 		-D introspection=disabled
 		-D libnice=disabled
-		-D omx=disabled
+		#-D omx=disabled
+		-D libnice=disabled
 		-D orc-source=system
 		-D package-origin="https://www.archlinux.org/"
 
@@ -203,6 +204,10 @@ build() {
 		-D gst-plugins-bad:msdk=disabled # due to no msdk (32-bit) support
 		-D gst-plugins-bad:qsv=disabled # due to no x86 support
 		-D gst-plugins-bad:ldac=disabled # due to no lib32-libdac support
+		-D gst-plugins-bad:aja=disabled
+		-D gst-plugins-bad:mfx_api=oneVPL
+		-D gst-plugins-bad:qt6d3d11=disabled
+
 		-D gst-plugins-bad:microdns=disabled # due to no lib32-microdns support
 		-D gst-plugins-bad:openaptx=disabled # due to no lib32-Xaptx support
 		-D gst-plugins-bad:openexr=disabled # due to no lib32-openexr support
@@ -211,6 +216,7 @@ build() {
 		-D gst-plugins-bad:svthevcenc=disabled # due to no lib32-svthevcenc support
 	#	-D gst-plugins-bad:svtav1=disabled # due to no lib32-svt-av1
 		-D gst-plugins-bad:wpe=disabled # due to no lib32-wpe support
+		-D gst-plugins-bad:lc3=disabled
 		-D gst-plugins-bad:zxing=disabled # due to no lib32-zxing support
 		-D gst-plugins-bad:amfcodec=disabled # only support windows
 		-D gst-plugins-ugly:sidplay=disabled
@@ -276,7 +282,7 @@ package_lib32-gst-plugins-bad-libs() {
 	closedcaption colormanagement
 	curl dash dc1394 de265 dtls dtsdec
 	faac faad fdkaac fluidsynthmidi
-	gme hls kate ladspa lv2 modplug
+	gme hls ladspa lv2 modplug
 	musepack neonhttpsrc
 	openal opusparse resindvd
 	rsvg rtmp sbc sctp smoothstreaming
 ```

with the installed lib32-libnice and lib32-svt-av1

**Comment by ahmubashshir** [comment]
they added new things... lemme check the upstream lib32-gst pkgbuild...

**Comment by ahmubashshir** [comment]
Can't seem to remove libnice dep completely... testing things again... I'll try to push today...

**Comment by ahmubashshir** [comment]
Finally managed to drop webrtc completely (dropping libnice requirement in the process)

**Comment by ahmubashshir** [comment]
> `WARNING: unexpected liborc library version 0.4.38 is being picked up by /usr/local/bin/orcc, which is version 0.4.37. This might be because orc was installed from source and is also installed via packages, and liborc from the wrong prefix is used. Check your system setup.`

check your system
